services:
  nestjsLibs:
    build: .
    container_name: nestjs-libs
    tty: true
    restart: always
    ports:
      - 3900:3900
      - 3901:3901
    volumes:
      - ./:/app
      - ./.docker/logs/npm:/home/node/.npm/_logs
      - ./.docker/logs/npm:/root/.npm/_logs
      - ~/.ssh:/home/node/.ssh
      - ~/.gitconfig:/home/node/.gitconfig
